//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTG_Helper.DAL.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MtgEntities : DbContext
    {
        public MtgEntities()
            : base("name=MtgEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CardColor> CardColors { get; set; }
        public virtual DbSet<Card> Cards { get; set; }
        public virtual DbSet<CardSet> CardSets { get; set; }
        public virtual DbSet<CardSubType> CardSubTypes { get; set; }
        public virtual DbSet<CardType> CardTypes { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Set> Sets { get; set; }
        public virtual DbSet<SubType> SubTypes { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<Deck> Decks { get; set; }
        public virtual DbSet<DeckCard> DeckCards { get; set; }
        public virtual DbSet<CardTag> CardTags { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
    }
}
